### ISSUE TITLE
Scripts for generating rotamer libraries from MD simulations

### ISSUE THREAD

**Issue by amin-sagar** [jgaines42/MEDFORD-rotamer-library#1]
Hello.

Thanks for this awesome work!

I am trying to generate rotamer libraries of additional non-standard amino acids using the method described in the MEDFORD paper, except I am using gaussian accelerated MD simulations instead of BE-METAD.
I am wondering if you can share your scripts to generate rotamer libraries from MD simulations/ensemble of structures.

Thanks,
Amin.

**Comment by jgaines42** [comment]
Hi Amin,
You would need to reach out to the primary investigator of the project, Yu-Shan Lin to get access to any scripts for running the simulations.
If you are asking about getting the rotamer library after the simulation, that would be fairly dependent on your simulation output. For each frame of the simulation, we calculated phi, psi, chi1, etc for each amino acid. After assigning each frame of the simulation to a phi/psi bin, we simply calculated the probability of each rotamer in each bin across all steps of the simulation.
Let me know if that helps!
Jennifer

**Comment by amin-sagar** [comment]
Thanks @jgaines42 
I will try to contact  Yu-Shan Lin.
I have two specific questions.
1) How are the weights from metadynamics calculations included in the probability calculation?
Do you generate a weighted histogram of phi-psi and bin the weights in the psi-phi bins along with the chi angles and then sum them? I am finding this step non-trivial and that's the primary reason I wanted to get help from your scripts.

2) What do the values of r1,r2,r3,r4 mean? I thought these were identifiers of chi angles. But, if I look at the Trp rotamer library for example.
```
TRP  -180 -180   471     2  3  0  0  0.000000     0.0     0.0     0.0     0.0 
TRP  -180 -180   471     3  1  0  0  0.000000     0.0     0.0     0.0     0.0 
TRP  -180 -180   471     3  2  0  0  0.000000     0.0     0.0     0.0     0.0 
TRP  -180 -180   471     3  3  0  0  0.000000     0.0     0.0     0.0     0.0 
TRP  -180 -170   309     1  1  0  0  0.288000    59.7   -82.5     0.0     0.0 
TRP  -180 -170   309     1  2  0  0  0.181000    66.0    -5.7     0.0     0.0 
TRP  -180 -170   309     1  3  0  0  0.469000    60.8    82.6     0.0     0.0 
TRP  -180 -170   309     2  1  0  0  0.026000   200.3  -118.3     0.0     0.0 
TRP  -180 -170   309     2  2  0  0  0.036000   201.5    50.7     0.0     0.0 
```
The first four lines have all chi angles equal to zero but the values of rn are different. Maybe it doesn't matter in this case as they have zero probability.
But, the lines
```
TRP  -180 -170   309     1  2  0  0  0.181000    66.0    -5.7     0.0     0.0 
TRP  -180 -170   309     2  2  0  0  0.036000   201.5    50.7     0.0     0.0
```
have the same r2 but the values of chi2 are -5.7 and 50.7.
Have I misunderstood the meaning of r1,r2...?

Thanks again for your help.
Best,
Amin.

**Comment by jgaines42** [comment]
1. The weights from the metadynamics simulations are not directly included in the probability calculation. First we bin all the data by phi/psi, then calculate the probability of each rotamer in that phi/psi bin. For example, if the simulation produced the following output:
```
phi	psi	chi1
-170	-170	60
-165	-170	180
-170	-170	180
-170	-170	60
-170	-170	300
-165	-170	60
```
We would take the 4 time steps at (-170, -170) and look at the probability of each chi1 rotamer in that bin. 
```
phi	psi	chi1
-170	-170	60
-170	-170	180
-170	-170	60
-170	-170	300
```
P(60) if (-170, -170) = 50%
P(180) if (-170, -170) = 25%
P(300) if (-170, -170) = 25%
Then repeat for (-165, -170)

2. r1, r2, r3, r4 indicate the rotamers. They should be read as combinations. Looking at the TRP file, there are rotamer combinations that were never seen in the simulation, so they have probabilities of 0:

```
# T  Phi  Psi  Count    r1 r2 r3 r4 Probabil  chi1Val chi2Val chi3Val chi4Val
TRP  -180 -180   471     1  1  0  0  0.340000    58.4   -87.6     0.0     0.0 
TRP  -180 -180   471     1  2  0  0  0.102000    63.1    -7.4     0.0     0.0 
TRP  -180 -180   471     1  3  0  0  0.516000    61.6    82.7     0.0     0.0 
TRP  -180 -180   471     2  1  0  0  0.017000   190.5  -111.2     0.0     0.0 
TRP  -180 -180   471     2  2  0  0  0.025000   191.1    62.7     0.0     0.0 
TRP  -180 -180   471     2  3  0  0  0.000000     0.0     0.0     0.0     0.0 
TRP  -180 -180   471     3  1  0  0  0.000000     0.0     0.0     0.0     0.0 
TRP  -180 -180   471     3  2  0  0  0.000000     0.0     0.0     0.0     0.0 
TRP  -180 -180   471     3  3  0  0  0.000000     0.0     0.0     0.0     0.0 
```
For example, at phi/psi of (-180, -180), the 3rd chi1 rotamer is never seen, so the last 3 rows shown above have probabilities of 0. The chi1Val/chi2Val are also left at 0 because those are calculated from the average of the values seen in that rotamer in the simulation. Sometimes the values for the same rotamer are very different because the structure is shifted towards the edge of a rotamer bin in that phi/psi configurations. That is seen in the TRP example:
```
TRP  -180 -170   309     1  2  0  0  0.181000    66.0    -5.7     0.0     0.0 
TRP  -180 -170   309     2  2  0  0  0.036000   201.5    50.7     0.0     0.0
```
where the chi2 rotamer is centered at -5.7 when chi1 is in rotamer 1 and at 50 when chi1 is in rotamer 2.

Hope that helps!

**Comment by amin-sagar** [comment]
Thanks @jgaines42 for the explanation.

Best,
Amin.
